# Generated by Django 2.1 on 2018-08-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvvrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='thread_date',
        ),
    ]
