# Generated by Django 2.1 on 2018-08-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srvvrs', '0003_remove_post_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thread_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='srvvrs.Thread'),
            preserve_default=False,
        ),
    ]
